# apiVersion: v1
# kind: Service
# metadata:
#   name: users-service
# spec:
#   selector:
#     app: users
#   type: LoadBalancer
#   ports:
#     - protocol: TCP
#       port: 8080
#       targetPort: 8080

apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    name: users
    role: app
    version: v1
  ports:
    - name: users-app-port
      protocol: TCP
      targetPort: 8080
      port: 80
  type: LoadBalancer