---
apiVersion: v1
kind: PersistentVolume
metadata: 
  name: host-pv
  labels:
    version: "1"
    role: "pv"
spec:
  capacity:
    storage: 1Gi
  volumeMode: FileSystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
  labels:
    version: "1"
    role: "pvc"
spec:
  volumeName: host-pv
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      version: "1"
      role: "pv"