apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-deployment
  labels:
    name: task
    role: app
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      name: task
  template:
    metadata:
      labels:
        name: task
        role: app
        version: v1
    spec:
      containers:
        - name: task-app
          image: ashish3yadav/task-app:v3
          env:
            - name: AUTH_ADDRESS
              value: 'auth-service.default.svc.cluster.local'
            - name: TASKS_FOLDER
              value: 'task'
          ports:
            - name: task-app-port
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
          resources:
            limits:
              cpu: "20m"   # Changed from "20Mi" to "20m"
              memory: "100Mi"
            requests:
              cpu: "10m"   # Changed from "10Mi" to "10m"
              memory: "50Mi"
          volumeMounts:
            - mountPath: /app/task
              name: task-volume
      volumes:
        - name: task-volume
          emptyDir:
            sizeLimit: '100Mi'
