
apiVersion: v1
kind: Service
metadata:
  name: task-service
  labels:
    name: task
spec:
  selector:
    name: task
    role: app
    version: v1
  ports:
    - name: task-app-port
      protocol: TCP
      targetPort: 8080
      port: 80
  type: LoadBalancer