
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  labels:
    name: jenkins-pvc
    role: pvc
    version: v1
spec:
  volumeName: jenkins-pv
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      name: jenkins-pv
      role: pv
      version: v1
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi