apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  labels:
    name: jenkins
    role: service
spec:
  selector:
    name: jenkins
    role: pod
  ports:
    - name: jenkins-port
      port: 80
      targetPort: 8080
    - name: jenkins-agent-port
      port: 5000
      targetPort: 50000
  type: LoadBalancer