apiVersion: v1
kind: Service
metadata:
  name: test-svc
  labels:
    role: test
spec:
  selector:
    test: jenkins-2
    role: pod
  ports:
    - name: jenkins-port
      port: 80
      targetPort: 8080
    - name: jenkins-agent-port
      port: 5000
      targetPort: 50000
  type: LoadBalancer