---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    name: auth
spec:
  selector:
    name: auth
    role: app
    version: v1
  clusterIp: None
  ports:
    - name: auth-app-port
      protocol: TCP
      targetPort: 8000
      port: 80
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: jenkins-service-2
#   labels:
#     name: jenkins
# spec:
#   selector:
#     name: jenkins
#   ports:
#     - name: jenkins-app-port
#       protocol: TCP
#       targetPort: 8080
#       port: 80