
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    name: auth
spec:
  selector:
    name: auth
    role: app
    version: v1
  ports:
    - name: auth-app-port
      protocol: TCP
      targetPort: 8000
      port: 80
  type: ClusterIP