---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service-2
  labels:
    name: jenkins
spec:
  selector:
    name: jenkins
  # clusterIP: None
  ports:
    - name: jenkins-app-port
      protocol: TCP
      targetPort: 8080
      port: 80
  type: LoadBalancer