apiVersion: v1
kind: Pod
metadata:
  name: centos-pod
spec:
  containers:
    - name: centos-os
      image: centos
      stdin: true
      tty: true
      resources:
        limits:
          memory: "500Mi"
        requests:
          memory: "200Mi"
