---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app-name: nginx
    role: app
    version: v1
  ports:
    - name: nginx-port
      protocol: 'TCP'
      targetPort: 80
      port: 80
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels: 
    app-name: nginx
    role: app
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app-name: nginx
      role: app
      version: v1
  template:
    metadata:
      name: nginx-pod
      labels: 
        app-name: nginx
        role: app
        version: v1
    spec:
      containers:
        - name: nginx-proxy-container
          image: nginx
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
          

