apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    role: app
    version: v2
spec:
  containers:
  - name: busybox
    image: busybox:latest
    command: ["sh", "-c", "echo 'Hello World && sleep 3600"]
  restartPolicy: OnFailure
