pipeline {
    agent any
    stages {
        stage('Checkout Repo'){
            steps{
                sh 'echo   "Not checking out the repo since already inside that repo"'
                sh 'ls -la'
            }
        }

        stage('Navigating to module directory and specific resource'){
            steps{
                dir("automatedTerraform/resource/${resource}"){
                    sh 'ls -la'
                    sh 'pwd'
                }
            }
        }

        stage('Initialising the terraform'){
            steps {
                dir("automatedTerraform/resource/${resource}"){
                    sh '/usr/local/bin/terraform init -reconfigure'
                }

            }
        }

        stage('Planning the terraforn resource'){
            steps {
                dir("automatedTerraform/resource/${resource}"){
                    sh '/usr/local/bin/terraform plan'
                }

            }
        }
    }
}
