pipeline {
    agent any
    stages {
        stage('Checkout Repo'){
            steps{
                sh 'echo   "Not checking out the repo since already inside that repo"'
                sh 'pwd'
                sh 'ls'
            }

        }
    }
}
